### PR TITLE
Add automatic crash detection

### PR DESCRIPTION
**Pull request by PintTheDragon**
One issue that's been showing up a lot over the past week or so are crashes that make a server unresponsive. To fix at least servers not automatically restarting from this issue, I propose a sort of "ping" between LocalAdmin and the server process, running under the main thread. This implements the handling of the ping on LocalAdmin, but sending the ping message also needs to be implemented ingame.

Here's an example implementation of such a pinger:
```csharp
private static IEnumerator<float> SendMessage()
{
    while (true)
    {
        ServerStatic.ServerOutput?.AddLog("­");
        yield return Timing.WaitForSeconds(1f);
    }
}
```

Essentially, every time a ping is received, the timer resets to 5. The timer is 20 at the start, and gets set back to 20 whenever the server isn't connected. Otherwise, it counts down every second, and kills the server once it hits zero.

The biggest challenge here is that idle mode will interfere with it and kill the server (hence why this is marked as a draft). Currently, I've been unable to get around this, as using Tasks defeats the whole purpose of this, and sending a message each frame is not very efficient (which is what I'm currently doing, and it does work, I just believe that there's a better way to do it).

### CODE REVIEW

**Comment by joker-119** [comment]
You could have the server send a message to LocalAdmin signaling when it's entering/exiting idle mode, and adjust the length of the timer based on the state the server is in.

**Comment by ced777ric** [comment]
Doesnt idle mode slow down coroutines?
Because if so yeah might be useful to add what joker mentioned.

**Comment by joker-119** [comment]
> Doesnt idle mode slow down coroutines? Because if so yeah might be useful to add what joker mentioned.

I'm pretty sure, yes, since they are still running on the main thread.

**Comment by PintTheDragon** [comment]
> You could have the server send a message to LocalAdmin signaling when it's entering/exiting idle mode, and adjust the length of the timer based on the state the server is in.

The issue with that is that it might be possible that the server crashes while in idle mode.



> Doesnt idle mode slow down coroutines? Because if so yeah might be useful to add what joker mentioned.

Yes. The solution I'm using is to send it every frame.

**Comment by PintTheDragon** [comment]
Currently in place:
```csharp
private static IEnumerator<float> SendMessage()
{
    while (true)
    {
        ServerStatic.ServerOutput?.AddLog("­");
        yield return Timing.WaitForOneFrame;
    }
}
```

It seems to be working, restarted the server correctly, and I've yet to encounter any performance issues with it.

**Comment by joker-119** [comment]
> > You could have the server send a message to LocalAdmin signaling when it's entering/exiting idle mode, and adjust the length of the timer based on the state the server is in.
> 
> The issue with that is that it might be possible that the server crashes while in idle mode.
That's why you adjust the timer, rather than suspending the crash detection entierly. Idlemode sets the tick frequency to 1/60th of normal, so if you multiply the current timer, and time added by 60, you should be safe while it's in idle mode without any other adjustments needed, the downside of which is it will take 60x longer than normal to detect a freeze if it occurs during idle mode.

**Comment by PintTheDragon** [comment]
> > > You could have the server send a message to LocalAdmin signaling when it's entering/exiting idle mode, and adjust the length of the timer based on the state the server is in.
> > 
> > 
> > The issue with that is that it might be possible that the server crashes while in idle mode.
> > That's why you adjust the timer, rather than suspending the crash detection entierly. Idlemode sets the tick frequency to 1/60th of normal, so if you multiply the current timer, and time added by 60, you should be safe while it's in idle mode without any other adjustments needed, the downside of which is it will take 60x longer than normal to detect a freeze if it occurs during idle mode.

I've already done this, and it didn't work. The issue is that that 1s becomes super long when idle mode happens, so to even say that idle mode is in progress, or modifying the delay, takes too much time. It might be possible for me to implement the timer myself though.

**Comment by zabszk** [comment]
Pull request #31 fixed broken process exit detection, so crashes should be now properly detected.

If we want to add unresponsive process detection we can send a ping command if the game doesn't output anything for a set period of time (eg. 20 seconds, should be configurable using startup args and/or LA config file) and we can use Output Codes as a ping reply.

**Comment by PintTheDragon** [comment]
> Pull request #31 fixed broken process exit detection, so crashes should be now properly detected.
> 
> If we want to add unresponsive process detection we can send a ping command if the game doesn't output anything for a set period of time (eg. 20 seconds, should be configurable using startup args and/or LA config file) and we can use Output Codes as a ping reply.

That's sort of what this does, though the pings come from SL and don't use responses. The biggest challenge I've had is dealing with idle mode correctly.

**Comment by zabszk** [comment]
> 
> 
> > Pull request #31 fixed broken process exit detection, so crashes should be now properly detected.
> > If we want to add unresponsive process detection we can send a ping command if the game doesn't output anything for a set period of time (eg. 20 seconds, should be configurable using startup args and/or LA config file) and we can use Output Codes as a ping reply.
> 
> That's sort of what this does, though the pings come from SL and don't use responses. The biggest challenge I've had is dealing with idle mode correctly.

The easiest way is to send the pings from a separated thread. That will deal with the idle mode, but will not detect freezes caused by main game thread being stuck somewhere.

**Comment by PintTheDragon** [comment]
> > > Pull request #31 fixed broken process exit detection, so crashes should be now properly detected.
> > > If we want to add unresponsive process detection we can send a ping command if the game doesn't output anything for a set period of time (eg. 20 seconds, should be configurable using startup args and/or LA config file) and we can use Output Codes as a ping reply.
> > 
> > 
> > That's sort of what this does, though the pings come from SL and don't use responses. The biggest challenge I've had is dealing with idle mode correctly.
> 
> The easiest way is to send the pings from a separated thread. That will deal with the idle mode, but will not detect freezes caused by main game thread being stuck somewhere.

That defeats the whole point of doing this though.

**Comment by zabszk** [comment]
Superseded by #47.

**Pull request closed without merging**
